Santa wants to analyze which toys that were produced in his workshop have already been delivered to children....

Question 1: Santa wants to analyze which toys that were produced in his workshop have already been delivered to children. You are given two tables on toy production and toy delivery — can you return the toy ID and toy name of the toys that have been delivered?
